-- Starter Piece values (CONTEXT.md): untradeable pieces of tradeable items, valued as (whole item − other pieces) ÷ N.
-- Added once, by no one in particular (created_by_user_id null); Admins own them from here (Site admin > Piece values).
-- A piece that already has a Piece value (matched case-insensitively, as the app does) is left alone.

INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Executioner''s axe head', 'Soulreaper axe', 4 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Executioner''s axe head'));--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Leviathan''s lure', 'Soulreaper axe', 4 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Leviathan''s lure'));--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Siren''s staff', 'Soulreaper axe', 4 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Siren''s staff'));--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Eye of the duke', 'Soulreaper axe', 4 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Eye of the duke'));--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Ultor vestige', 'Ultor ring', 1 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Ultor vestige'));--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Berserker ring', 1 FROM `piece_values` WHERE `piece_item_name` = 'Ultor vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Chromium ingot', 3 FROM `piece_values` WHERE `piece_item_name` = 'Ultor vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Bellator vestige', 'Bellator ring', 1 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Bellator vestige'));--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Warrior ring', 1 FROM `piece_values` WHERE `piece_item_name` = 'Bellator vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Chromium ingot', 3 FROM `piece_values` WHERE `piece_item_name` = 'Bellator vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Magus vestige', 'Magus ring', 1 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Magus vestige'));--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Seers ring', 1 FROM `piece_values` WHERE `piece_item_name` = 'Magus vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Chromium ingot', 3 FROM `piece_values` WHERE `piece_item_name` = 'Magus vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Venator vestige', 'Venator ring', 1 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Venator vestige'));--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Archers ring', 1 FROM `piece_values` WHERE `piece_item_name` = 'Venator vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Chromium ingot', 3 FROM `piece_values` WHERE `piece_item_name` = 'Venator vestige' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Araxyte fang', 'Amulet of rancour', 1 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Araxyte fang'));--> statement-breakpoint
INSERT OR IGNORE INTO `piece_value_other_pieces` (`id`, `piece_value_id`, `item_name`, `quantity`) SELECT lower(hex(randomblob(16))), `id`, 'Amulet of torture', 1 FROM `piece_values` WHERE `piece_item_name` = 'Araxyte fang' AND `created_by_user_id` IS NULL;--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Hydra''s fang', 'Brimstone ring', 3 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Hydra''s fang'));--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Hydra''s eye', 'Brimstone ring', 3 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Hydra''s eye'));--> statement-breakpoint
INSERT INTO `piece_values` (`id`, `piece_item_name`, `whole_item_name`, `divisor`) SELECT lower(hex(randomblob(16))), 'Hydra''s heart', 'Brimstone ring', 3 WHERE NOT EXISTS (SELECT 1 FROM `piece_values` WHERE lower(`piece_item_name`) = lower('Hydra''s heart'));
